# Generated by Django 4.2.5 on 2023-10-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_profile_address_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='about',
            field=models.TextField(default='Shop', verbose_name='About page content'),
            preserve_default=False,
        ),
    ]
