# Generated by Django 4.2.5 on 2023-10-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_gender_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstyle',
            name='img',
            field=models.ImageField(default='1', upload_to='product_brands/'),
            preserve_default=False,
        ),
    ]
