# Generated by Django 4.2.5 on 2023-10-24 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_cartitem_product_alter_cartitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='size_orders', to='shop.size'),
            preserve_default=False,
        ),
    ]
