# Generated by Django 4.2.5 on 2023-10-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='sample', max_length=500),
            preserve_default=False,
        ),
    ]
