# Generated by Django 4.2.5 on 2023-10-29 03:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
