# Generated by Django 4.2.5 on 2023-10-29 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstyle',
            name='slug',
        ),
    ]
